name: Run Chat Copier

# מגדיר שהסקריפט ירוץ בלחיצת כפתור ידנית מהממשק
on:
  workflow_dispatch: 

jobs:
  copy-message:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib requests

    - name: Run the script
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        GCP_TOKEN: ${{ secrets.GCP_TOKEN }}
      run: python main.py
